// Morpheme database for the etymology engine.
// Each entry describes a building block of English words derived mainly from
// Latin and Greek. `forms` lists the surface spellings that can appear in a
// real word (including assimilated / combining variants). `origin` is the
// source language, `source` is the original word/element in that language,
// and `meaning` is a short gloss used to build a literal reading.

const MORPHEMES = {
  prefixes: [
    { id: "a-priv", forms: ["an", "a"], origin: "Greek", source: "a-/an-", meaning: "not, without" },
    { id: "ab", forms: ["abs", "ab"], origin: "Latin", source: "ab", meaning: "away from" },
    { id: "ad", forms: ["ac", "af", "ag", "al", "ap", "as", "at", "ad", "a"], origin: "Latin", source: "ad", meaning: "to, toward" },
    { id: "ambi", forms: ["ambi", "amphi"], origin: "Latin", source: "ambi", meaning: "both, around" },
    { id: "ante", forms: ["ante", "anti"], origin: "Latin", source: "ante", meaning: "before" },
    { id: "anti", forms: ["anti", "ant"], origin: "Greek", source: "anti", meaning: "against, opposite" },
    { id: "auto", forms: ["auto", "aut"], origin: "Greek", source: "autos", meaning: "self" },
    { id: "bene", forms: ["bene", "ben"], origin: "Latin", source: "bene", meaning: "well, good" },
    { id: "bi", forms: ["bi"], origin: "Latin", source: "bi-", meaning: "two" },
    { id: "circum", forms: ["circum", "circu"], origin: "Latin", source: "circum", meaning: "around" },
    { id: "co", forms: ["com", "con", "col", "cor", "co"], origin: "Latin", source: "com", meaning: "with, together" },
    { id: "contra", forms: ["contra", "contro", "counter"], origin: "Latin", source: "contra", meaning: "against" },
    { id: "de", forms: ["de"], origin: "Latin", source: "de", meaning: "down, away, off" },
    { id: "dia", forms: ["dia", "di"], origin: "Greek", source: "dia", meaning: "through, across" },
    { id: "dis", forms: ["dif", "dis", "di"], origin: "Latin", source: "dis", meaning: "apart, not" },
    { id: "dys", forms: ["dys"], origin: "Greek", source: "dys", meaning: "bad, difficult" },
    { id: "e", forms: ["ex", "ef", "e"], origin: "Latin", source: "ex", meaning: "out, out of" },
    { id: "ecto", forms: ["ecto", "ect"], origin: "Greek", source: "ektos", meaning: "outside" },
    { id: "en", forms: ["em", "en"], origin: "Greek", source: "en", meaning: "in, into" },
    { id: "endo", forms: ["endo", "end"], origin: "Greek", source: "endon", meaning: "within" },
    { id: "epi", forms: ["epi", "ep"], origin: "Greek", source: "epi", meaning: "upon, over" },
    { id: "eu", forms: ["eu"], origin: "Greek", source: "eu", meaning: "good, well" },
    { id: "extra", forms: ["extra", "extro"], origin: "Latin", source: "extra", meaning: "outside, beyond" },
    { id: "fore", forms: ["fore"], origin: "Old English", source: "fore", meaning: "before, in front" },
    { id: "hemi", forms: ["hemi"], origin: "Greek", source: "hemi", meaning: "half" },
    { id: "hetero", forms: ["hetero", "heter"], origin: "Greek", source: "heteros", meaning: "different, other" },
    { id: "homo", forms: ["homo", "hom"], origin: "Greek", source: "homos", meaning: "same" },
    { id: "hyper", forms: ["hyper"], origin: "Greek", source: "hyper", meaning: "over, excessive" },
    { id: "hypo", forms: ["hypo", "hyp"], origin: "Greek", source: "hypo", meaning: "under, below" },
    { id: "in-neg", forms: ["il", "im", "ir", "in"], origin: "Latin", source: "in-", meaning: "not" },
    { id: "in-loc", forms: ["im", "in"], origin: "Latin", source: "in", meaning: "in, into" },
    { id: "inter", forms: ["inter", "intel"], origin: "Latin", source: "inter", meaning: "between, among" },
    { id: "intra", forms: ["intra", "intro"], origin: "Latin", source: "intra", meaning: "within" },
    { id: "macro", forms: ["macro", "macr"], origin: "Greek", source: "makros", meaning: "large, long" },
    { id: "mal", forms: ["male", "mal"], origin: "Latin", source: "malus", meaning: "bad, ill" },
    { id: "mega", forms: ["mega", "megal"], origin: "Greek", source: "megas", meaning: "great, large" },
    { id: "meta", forms: ["meta", "met"], origin: "Greek", source: "meta", meaning: "beyond, change" },
    { id: "micro", forms: ["micro", "micr"], origin: "Greek", source: "mikros", meaning: "small" },
    { id: "mid", forms: ["mid"], origin: "Old English", source: "midd", meaning: "middle" },
    { id: "mis", forms: ["mis"], origin: "Old English", source: "mis-", meaning: "wrong, badly" },
    { id: "mono", forms: ["mono", "mon"], origin: "Greek", source: "monos", meaning: "one, single" },
    { id: "multi", forms: ["multi", "mult"], origin: "Latin", source: "multus", meaning: "many" },
    { id: "neo", forms: ["neo", "ne"], origin: "Greek", source: "neos", meaning: "new" },
    { id: "non", forms: ["non"], origin: "Latin", source: "non", meaning: "not" },
    { id: "ob", forms: ["oc", "of", "op", "ob"], origin: "Latin", source: "ob", meaning: "against, toward" },
    { id: "omni", forms: ["omni"], origin: "Latin", source: "omnis", meaning: "all" },
    { id: "para", forms: ["para", "par"], origin: "Greek", source: "para", meaning: "beside, beyond" },
    { id: "per", forms: ["per"], origin: "Latin", source: "per", meaning: "through, thoroughly" },
    { id: "peri", forms: ["peri"], origin: "Greek", source: "peri", meaning: "around" },
    { id: "poly", forms: ["poly"], origin: "Greek", source: "polys", meaning: "many" },
    { id: "post", forms: ["post"], origin: "Latin", source: "post", meaning: "after" },
    { id: "pre", forms: ["pre"], origin: "Latin", source: "prae", meaning: "before" },
    { id: "pro", forms: ["pro"], origin: "Latin", source: "pro", meaning: "forward, for" },
    { id: "proto", forms: ["proto", "prot"], origin: "Greek", source: "protos", meaning: "first" },
    { id: "pseudo", forms: ["pseudo", "pseud"], origin: "Greek", source: "pseudes", meaning: "false" },
    { id: "quasi", forms: ["quasi"], origin: "Latin", source: "quasi", meaning: "as if, almost" },
    { id: "re", forms: ["re"], origin: "Latin", source: "re-", meaning: "again, back" },
    { id: "retro", forms: ["retro"], origin: "Latin", source: "retro", meaning: "backward" },
    { id: "se", forms: ["se"], origin: "Latin", source: "se-", meaning: "apart, aside" },
    { id: "semi", forms: ["semi"], origin: "Latin", source: "semi", meaning: "half" },
    { id: "sub", forms: ["suc", "suf", "sug", "sup", "sus", "sub"], origin: "Latin", source: "sub", meaning: "under, below" },
    { id: "super", forms: ["super", "sur"], origin: "Latin", source: "super", meaning: "above, over" },
    { id: "syn", forms: ["sym", "syl", "syn", "sy"], origin: "Greek", source: "syn", meaning: "with, together" },
    { id: "tele", forms: ["tele", "tel"], origin: "Greek", source: "tele", meaning: "far, distant" },
    { id: "trans", forms: ["trans", "tran"], origin: "Latin", source: "trans", meaning: "across, beyond" },
    { id: "tri", forms: ["tri"], origin: "Latin", source: "tri-", meaning: "three" },
    { id: "ultra", forms: ["ultra"], origin: "Latin", source: "ultra", meaning: "beyond, excessive" },
    { id: "un", forms: ["un"], origin: "Old English", source: "un-", meaning: "not, reverse of" },
    { id: "uni", forms: ["uni"], origin: "Latin", source: "unus", meaning: "one" },
    { id: "vice", forms: ["vice"], origin: "Latin", source: "vice", meaning: "in place of" }
  ],

  roots: [
    { id: "anthrop", forms: ["anthrop"], origin: "Greek", source: "anthropos", meaning: "human being" },
    { id: "aqua", forms: ["aqua", "aque", "aqui"], origin: "Latin", source: "aqua", meaning: "water" },
    { id: "arch", forms: ["arch"], origin: "Greek", source: "arkhe", meaning: "chief, rule, beginning" },
    { id: "aster", forms: ["astro", "aster", "astr"], origin: "Greek", source: "aster", meaning: "star" },
    { id: "aud", forms: ["audi", "audit", "aud"], origin: "Latin", source: "audire", meaning: "to hear" },
    { id: "bell", forms: ["belli", "bell"], origin: "Latin", source: "bellum", meaning: "war" },
    { id: "bio", forms: ["bio", "bi"], origin: "Greek", source: "bios", meaning: "life" },
    { id: "brev", forms: ["brevi", "brev"], origin: "Latin", source: "brevis", meaning: "short" },
    { id: "cap", forms: ["ceive", "ceipt", "ceit", "ceiv", "capt", "cept", "cip", "cap"], origin: "Latin", source: "capere", meaning: "to take, seize" },
    { id: "cardi", forms: ["cardio", "cardi"], origin: "Greek", source: "kardia", meaning: "heart" },
    { id: "carn", forms: ["carni", "carn"], origin: "Latin", source: "caro", meaning: "flesh" },
    { id: "ced", forms: ["cess", "ceed", "ced"], origin: "Latin", source: "cedere", meaning: "to go, yield" },
    { id: "centr", forms: ["centr"], origin: "Greek", source: "kentron", meaning: "center, point" },
    { id: "chron", forms: ["chrono", "chron"], origin: "Greek", source: "khronos", meaning: "time" },
    { id: "cide", forms: ["cide", "cis"], origin: "Latin", source: "caedere", meaning: "to kill, cut" },
    { id: "claim", forms: ["claim", "clam"], origin: "Latin", source: "clamare", meaning: "to shout, cry out" },
    { id: "clud", forms: ["clud", "clus", "clos"], origin: "Latin", source: "claudere", meaning: "to close, shut" },
    { id: "cogn", forms: ["cogni", "cogn", "gnos"], origin: "Latin", source: "cognoscere", meaning: "to know" },
    { id: "corp", forms: ["corpor", "corp"], origin: "Latin", source: "corpus", meaning: "body" },
    { id: "cosm", forms: ["cosmo", "cosm"], origin: "Greek", source: "kosmos", meaning: "world, order" },
    { id: "cred", forms: ["credit", "cred"], origin: "Latin", source: "credere", meaning: "to believe" },
    { id: "crat", forms: ["cracy", "crat"], origin: "Greek", source: "kratos", meaning: "power, rule" },
    { id: "cred2", forms: ["cred"], origin: "Latin", source: "credere", meaning: "to believe, trust" },
    { id: "curr", forms: ["curr", "curs", "cours"], origin: "Latin", source: "currere", meaning: "to run" },
    { id: "dem", forms: ["demo", "dem"], origin: "Greek", source: "demos", meaning: "people" },
    { id: "dent", forms: ["dent"], origin: "Latin", source: "dens", meaning: "tooth" },
    { id: "derm", forms: ["dermato", "dermat", "derm"], origin: "Greek", source: "derma", meaning: "skin" },
    { id: "dic", forms: ["dict", "dic"], origin: "Latin", source: "dicere", meaning: "to say, speak" },
    { id: "doc", forms: ["doct", "doc"], origin: "Latin", source: "docere", meaning: "to teach" },
    { id: "domin", forms: ["domin"], origin: "Latin", source: "dominus", meaning: "master, lord" },
    { id: "duc", forms: ["duct", "duc"], origin: "Latin", source: "ducere", meaning: "to lead" },
    { id: "dyn", forms: ["dynamo", "dynam", "dyn"], origin: "Greek", source: "dynamis", meaning: "power, force" },
    { id: "fac", forms: ["fact", "fect", "fic", "fac"], origin: "Latin", source: "facere", meaning: "to make, do" },
    { id: "fer", forms: ["fer"], origin: "Latin", source: "ferre", meaning: "to bear, carry" },
    { id: "fid", forms: ["fid"], origin: "Latin", source: "fides", meaning: "faith, trust" },
    { id: "fin", forms: ["fin"], origin: "Latin", source: "finis", meaning: "end, limit" },
    { id: "flect", forms: ["flect", "flex"], origin: "Latin", source: "flectere", meaning: "to bend" },
    { id: "flu", forms: ["fluc", "flux", "flu"], origin: "Latin", source: "fluere", meaning: "to flow" },
    { id: "form", forms: ["form"], origin: "Latin", source: "forma", meaning: "shape, form" },
    { id: "fort", forms: ["fort"], origin: "Latin", source: "fortis", meaning: "strong" },
    { id: "frag", forms: ["fract", "frag"], origin: "Latin", source: "frangere", meaning: "to break" },
    { id: "gen", forms: ["gener", "gene", "gen"], origin: "Greek", source: "genos", meaning: "birth, kind, origin" },
    { id: "geo", forms: ["geo", "ge"], origin: "Greek", source: "ge", meaning: "earth" },
    { id: "grad", forms: ["gress", "grad"], origin: "Latin", source: "gradi", meaning: "to step, go" },
    { id: "graph", forms: ["graph", "gram"], origin: "Greek", source: "graphein", meaning: "to write, draw" },
    { id: "grat", forms: ["grati", "grat"], origin: "Latin", source: "gratus", meaning: "pleasing, thankful" },
    { id: "greg", forms: ["greg"], origin: "Latin", source: "grex", meaning: "flock, herd" },
    { id: "helio", forms: ["helio", "heli"], origin: "Greek", source: "helios", meaning: "sun" },
    { id: "hydr", forms: ["hydro", "hydr"], origin: "Greek", source: "hydor", meaning: "water" },
    { id: "ject", forms: ["ject", "jac"], origin: "Latin", source: "iacere", meaning: "to throw" },
    { id: "jud", forms: ["judic", "jud"], origin: "Latin", source: "iudex", meaning: "judge, law" },
    { id: "junct", forms: ["junct", "join", "jug"], origin: "Latin", source: "iungere", meaning: "to join" },
    { id: "leg", forms: ["legis", "leg"], origin: "Latin", source: "lex", meaning: "law" },
    { id: "lect", forms: ["lect", "leg", "lig"], origin: "Latin", source: "legere", meaning: "to read, choose, gather" },
    { id: "liber", forms: ["liber", "liver"], origin: "Latin", source: "liber", meaning: "free" },
    { id: "lingu", forms: ["lingu"], origin: "Latin", source: "lingua", meaning: "tongue, language" },
    { id: "loc", forms: ["loc"], origin: "Latin", source: "locus", meaning: "place" },
    { id: "log", forms: ["logue", "logy", "log"], origin: "Greek", source: "logos", meaning: "word, study, reason" },
    { id: "luc", forms: ["lumin", "luc", "lustr"], origin: "Latin", source: "lux", meaning: "light" },
    { id: "magn", forms: ["magni", "magn"], origin: "Latin", source: "magnus", meaning: "great, large" },
    { id: "man", forms: ["manu", "man"], origin: "Latin", source: "manus", meaning: "hand" },
    { id: "mar", forms: ["marin", "mar"], origin: "Latin", source: "mare", meaning: "sea" },
    { id: "mater", forms: ["matri", "mater", "matr"], origin: "Latin", source: "mater", meaning: "mother" },
    { id: "ment", forms: ["mente", "ment"], origin: "Latin", source: "mens", meaning: "mind" },
    { id: "meter", forms: ["meter", "metr"], origin: "Greek", source: "metron", meaning: "measure" },
    { id: "migr", forms: ["migr"], origin: "Latin", source: "migrare", meaning: "to move, wander" },
    { id: "mit", forms: ["miss", "mit"], origin: "Latin", source: "mittere", meaning: "to send" },
    { id: "mort", forms: ["mort"], origin: "Latin", source: "mors", meaning: "death" },
    { id: "mot", forms: ["mot", "mov", "mob"], origin: "Latin", source: "movere", meaning: "to move" },
    { id: "mut", forms: ["mut"], origin: "Latin", source: "mutare", meaning: "to change" },
    { id: "nat", forms: ["nat", "nasc"], origin: "Latin", source: "nasci", meaning: "to be born" },
    { id: "nav", forms: ["navig", "naut", "nav"], origin: "Latin", source: "navis", meaning: "ship" },
    { id: "necr", forms: ["necro", "necr"], origin: "Greek", source: "nekros", meaning: "death, corpse" },
    { id: "nom", forms: ["nomin", "nom"], origin: "Latin", source: "nomen", meaning: "name" },
    { id: "nov", forms: ["nov"], origin: "Latin", source: "novus", meaning: "new" },
    { id: "ocul", forms: ["ocul"], origin: "Latin", source: "oculus", meaning: "eye" },
    { id: "onym", forms: ["onym", "onom"], origin: "Greek", source: "onyma", meaning: "name" },
    { id: "op", forms: ["oper", "op"], origin: "Latin", source: "opus", meaning: "work" },
    { id: "opt", forms: ["optic", "opt"], origin: "Greek", source: "optos", meaning: "eye, sight" },
    { id: "orth", forms: ["ortho", "orth"], origin: "Greek", source: "orthos", meaning: "straight, correct" },
    { id: "pan", forms: ["pan", "pant"], origin: "Greek", source: "pan", meaning: "all" },
    { id: "pachy", forms: ["pachy", "pach"], origin: "Greek", source: "pakhys", meaning: "thick" },
    { id: "path", forms: ["patho", "path"], origin: "Greek", source: "pathos", meaning: "feeling, suffering" },
    { id: "pater", forms: ["patri", "pater", "patr"], origin: "Latin", source: "pater", meaning: "father" },
    { id: "ped-foot", forms: ["ped", "pod"], origin: "Latin", source: "pes", meaning: "foot" },
    { id: "ped-child", forms: ["pedo", "ped"], origin: "Greek", source: "pais", meaning: "child" },
    { id: "pel", forms: ["puls", "pel"], origin: "Latin", source: "pellere", meaning: "to drive, push" },
    { id: "pend", forms: ["pend", "pens"], origin: "Latin", source: "pendere", meaning: "to hang, weigh" },
    { id: "phil", forms: ["philo", "phil"], origin: "Greek", source: "philos", meaning: "loving, fond of" },
    { id: "phob", forms: ["phobia", "phob"], origin: "Greek", source: "phobos", meaning: "fear" },
    { id: "phon", forms: ["phono", "phon"], origin: "Greek", source: "phone", meaning: "sound, voice" },
    { id: "photo", forms: ["photo", "phot"], origin: "Greek", source: "phos", meaning: "light" },
    { id: "phys", forms: ["physio", "phys"], origin: "Greek", source: "physis", meaning: "nature" },
    { id: "plic", forms: ["plic", "ploy", "ply", "plex"], origin: "Latin", source: "plicare", meaning: "to fold" },
    { id: "pon", forms: ["pos", "pon", "posit"], origin: "Latin", source: "ponere", meaning: "to place, put" },
    { id: "port", forms: ["port"], origin: "Latin", source: "portare", meaning: "to carry" },
    { id: "psych", forms: ["psycho", "psych"], origin: "Greek", source: "psyche", meaning: "mind, soul" },
    { id: "quir", forms: ["quir", "quis", "quest", "quer"], origin: "Latin", source: "quaerere", meaning: "to seek, ask" },
    { id: "reg", forms: ["rect", "reg"], origin: "Latin", source: "regere", meaning: "to rule, straighten" },
    { id: "rupt", forms: ["rupt"], origin: "Latin", source: "rumpere", meaning: "to break, burst" },
    { id: "sci", forms: ["scien", "sci"], origin: "Latin", source: "scire", meaning: "to know" },
    { id: "scop", forms: ["scope", "scop"], origin: "Greek", source: "skopein", meaning: "to look at, examine" },
    { id: "scrib", forms: ["script", "scrib"], origin: "Latin", source: "scribere", meaning: "to write" },
    { id: "sect", forms: ["sect", "seg"], origin: "Latin", source: "secare", meaning: "to cut" },
    { id: "sens", forms: ["sens", "sent"], origin: "Latin", source: "sentire", meaning: "to feel, perceive" },
    { id: "sequ", forms: ["sequ", "secut", "su"], origin: "Latin", source: "sequi", meaning: "to follow" },
    { id: "serv", forms: ["serv"], origin: "Latin", source: "servare", meaning: "to keep, save, serve" },
    { id: "sign", forms: ["sign"], origin: "Latin", source: "signum", meaning: "sign, mark" },
    { id: "sol", forms: ["sol"], origin: "Latin", source: "sol", meaning: "sun" },
    { id: "solv", forms: ["solv", "solut", "solu"], origin: "Latin", source: "solvere", meaning: "to loosen, free" },
    { id: "soph", forms: ["sophi", "soph"], origin: "Greek", source: "sophia", meaning: "wisdom" },
    { id: "spec", forms: ["spect", "spic", "spec"], origin: "Latin", source: "specere", meaning: "to look, see" },
    { id: "spir", forms: ["spir"], origin: "Latin", source: "spirare", meaning: "to breathe" },
    { id: "stru", forms: ["struct", "stru"], origin: "Latin", source: "struere", meaning: "to build" },
    { id: "tact", forms: ["tact", "tang", "ting"], origin: "Latin", source: "tangere", meaning: "to touch" },
    { id: "techn", forms: ["techno", "techn"], origin: "Greek", source: "tekhne", meaning: "art, skill, craft" },
    { id: "tele2", forms: ["tele"], origin: "Greek", source: "tele", meaning: "far, distant" },
    { id: "tempor", forms: ["tempor", "temp"], origin: "Latin", source: "tempus", meaning: "time" },
    { id: "ten", forms: ["tain", "ten", "tin"], origin: "Latin", source: "tenere", meaning: "to hold" },
    { id: "tend", forms: ["tend", "tens", "tent"], origin: "Latin", source: "tendere", meaning: "to stretch" },
    { id: "terr", forms: ["terr"], origin: "Latin", source: "terra", meaning: "earth, land" },
    { id: "theo", forms: ["theo", "the"], origin: "Greek", source: "theos", meaning: "god" },
    { id: "therm", forms: ["thermo", "therm"], origin: "Greek", source: "thermos", meaning: "heat" },
    { id: "tort", forms: ["tort", "tors"], origin: "Latin", source: "torquere", meaning: "to twist" },
    { id: "tract", forms: ["tract", "treat"], origin: "Latin", source: "trahere", meaning: "to pull, drag" },
    { id: "vac", forms: ["vacu", "vac"], origin: "Latin", source: "vacare", meaning: "to be empty" },
    { id: "ven", forms: ["vent", "ven"], origin: "Latin", source: "venire", meaning: "to come" },
    { id: "ver", forms: ["veri", "ver"], origin: "Latin", source: "verus", meaning: "true" },
    { id: "verb", forms: ["verb"], origin: "Latin", source: "verbum", meaning: "word" },
    { id: "vert", forms: ["vert", "vers"], origin: "Latin", source: "vertere", meaning: "to turn" },
    { id: "vid", forms: ["vid", "vis"], origin: "Latin", source: "videre", meaning: "to see" },
    { id: "vinc", forms: ["vinc", "vict"], origin: "Latin", source: "vincere", meaning: "to conquer" },
    { id: "viv", forms: ["vivi", "viv", "vit"], origin: "Latin", source: "vivere", meaning: "to live" },
    { id: "voc", forms: ["voc", "vok"], origin: "Latin", source: "vocare", meaning: "to call, voice" },
    { id: "vor", forms: ["vor"], origin: "Latin", source: "vorare", meaning: "to devour, eat" },
    { id: "volv", forms: ["volv", "volut", "volu"], origin: "Latin", source: "volvere", meaning: "to roll, turn" },
    { id: "zo", forms: ["zoo", "zo"], origin: "Greek", source: "zoion", meaning: "animal, living being" }
  ],

  suffixes: [
    { id: "able", forms: ["able", "ible", "ble"], origin: "Latin", source: "-abilis", meaning: "able to be, capable of" },
    { id: "acy", forms: ["acy", "cy"], origin: "Greek/Latin", source: "-cy", meaning: "state or quality of" },
    { id: "al", forms: ["al"], origin: "Latin", source: "-alis", meaning: "relating to" },
    { id: "ance", forms: ["ance", "ence", "ancy", "ency"], origin: "Latin", source: "-antia", meaning: "state or quality of" },
    { id: "ant", forms: ["ant", "ent"], origin: "Latin", source: "-ans", meaning: "one who, having the quality of" },
    { id: "ar", forms: ["ar"], origin: "Latin", source: "-aris", meaning: "relating to" },
    { id: "ary", forms: ["ary", "ery", "ory"], origin: "Latin", source: "-arius", meaning: "relating to, place for" },
    { id: "ate", forms: ["ate"], origin: "Latin", source: "-atus", meaning: "to make, cause; having" },
    { id: "cracy", forms: ["cracy"], origin: "Greek", source: "-kratia", meaning: "rule, government by" },
    { id: "cy", forms: ["cy"], origin: "Latin", source: "-cia", meaning: "state, condition" },
    { id: "dom", forms: ["dom"], origin: "Old English", source: "-dom", meaning: "state, realm, condition" },
    { id: "ed", forms: ["ed"], origin: "Old English", source: "-ed", meaning: "past tense; having" },
    { id: "en", forms: ["en"], origin: "Old English", source: "-en", meaning: "made of; to make" },
    { id: "ence", forms: ["ence", "ency"], origin: "Latin", source: "-entia", meaning: "state or quality of" },
    { id: "er-agent", forms: ["ator", "itor", "er", "or", "ar"], origin: "Latin/Old English", source: "-or / -er", meaning: "one who, that which" },
    { id: "esque", forms: ["esque"], origin: "French", source: "-esque", meaning: "in the style of, like" },
    { id: "ess", forms: ["ess"], origin: "French", source: "-esse", meaning: "female" },
    { id: "est", forms: ["est"], origin: "Old English", source: "-est", meaning: "most (superlative)" },
    { id: "ful", forms: ["ful"], origin: "Old English", source: "-full", meaning: "full of" },
    { id: "fy", forms: ["ify", "fy"], origin: "Latin", source: "-ficare", meaning: "to make, cause to become" },
    { id: "hood", forms: ["hood"], origin: "Old English", source: "-had", meaning: "state, condition, group" },
    { id: "ian", forms: ["ian", "an"], origin: "Latin", source: "-ianus", meaning: "relating to, one who" },
    { id: "ic", forms: ["ical", "ic"], origin: "Greek/Latin", source: "-ikos", meaning: "relating to, characterized by" },
    { id: "ify", forms: ["ify"], origin: "Latin", source: "-ificare", meaning: "to make into" },
    { id: "ile", forms: ["ile"], origin: "Latin", source: "-ilis", meaning: "capable of, relating to" },
    { id: "ine", forms: ["ine"], origin: "Latin", source: "-inus", meaning: "relating to, of the nature of" },
    { id: "ion", forms: ["ation", "ition", "sion", "tion", "ion"], origin: "Latin", source: "-io", meaning: "act, process, or result of" },
    { id: "ish", forms: ["ish"], origin: "Old English", source: "-isc", meaning: "having the quality of, somewhat" },
    { id: "ism", forms: ["ism"], origin: "Greek", source: "-ismos", meaning: "doctrine, belief, practice of" },
    { id: "ist", forms: ["ist"], origin: "Greek", source: "-istes", meaning: "one who practices or believes" },
    { id: "ity", forms: ["ity", "ety", "ty"], origin: "Latin", source: "-itas", meaning: "state or quality of" },
    { id: "ive", forms: ["ative", "itive", "ive"], origin: "Latin", source: "-ivus", meaning: "tending to, having the nature of" },
    { id: "ize", forms: ["ize", "ise"], origin: "Greek", source: "-izein", meaning: "to make, to become" },
    { id: "less", forms: ["less"], origin: "Old English", source: "-leas", meaning: "without, lacking" },
    { id: "logy", forms: ["ology", "logy"], origin: "Greek", source: "-logia", meaning: "study or science of" },
    { id: "ly", forms: ["ly"], origin: "Old English", source: "-lice", meaning: "in the manner of" },
    { id: "ment", forms: ["ment"], origin: "Latin", source: "-mentum", meaning: "result or means of an action" },
    { id: "ness", forms: ["ness"], origin: "Old English", source: "-nes", meaning: "state or quality of" },
    { id: "oid", forms: ["oid"], origin: "Greek", source: "-oeides", meaning: "resembling, like" },
    { id: "ory", forms: ["ory"], origin: "Latin", source: "-orius", meaning: "relating to; place for" },
    { id: "ous", forms: ["eous", "ious", "ous"], origin: "Latin", source: "-osus", meaning: "full of, having" },
    { id: "phobia", forms: ["phobia"], origin: "Greek", source: "-phobia", meaning: "fear of" },
    { id: "phy", forms: ["graphy", "phy"], origin: "Greek", source: "-graphia", meaning: "writing, recording, description" },
    { id: "ship", forms: ["ship"], origin: "Old English", source: "-scipe", meaning: "state, skill, or office of" },
    { id: "sis", forms: ["osis", "sis"], origin: "Greek", source: "-sis", meaning: "process, condition, action" },
    { id: "tude", forms: ["itude", "tude"], origin: "Latin", source: "-tudo", meaning: "state or quality of" },
    { id: "ty", forms: ["ty"], origin: "Latin", source: "-tas", meaning: "state or quality of" },
    { id: "ure", forms: ["ture", "ure", "tur", "ur"], origin: "Latin", source: "-ura", meaning: "act, process, or result of" },
    { id: "y", forms: ["y"], origin: "Old English", source: "-ig", meaning: "characterized by, full of" }
  ]
};

// Expose on the global object. A top-level `const` does not attach to `window`
// in the browser, so do it explicitly — otherwise engine.js can't see the data
// and the app reports "the dictionary didn't load".
(typeof window !== "undefined" ? window : globalThis).MORPHEMES = MORPHEMES;

if (typeof module !== "undefined" && module.exports) {
  module.exports = { MORPHEMES };
}
